export const ACTION_TYPE = {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    LOGOUT: "LOGOUT",
    SET_USER: "SET_USER",
    SET_EVENT_DATA: "SET_EVENT_DATA",
    RESET_EVENT_DATA: "RESET_EVENT_DATA",
}